// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	message.proto
	person.proto

It has these top-level messages:
	UserInfo
	SearchRequest
	SearchResponse
	Result
*/
package proto

import proto1 "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type FOO int32

const (
	FOO_X FOO = 0
)

var FOO_name = map[int32]string{
	0: "X",
}
var FOO_value = map[string]int32{
	"X": 0,
}

func (x FOO) String() string {
	return proto1.EnumName(FOO_name, int32(x))
}
func (FOO) EnumDescriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0} }

// message是固定的。UserInfo是类名，可以随意指定，符合规范即可
type UserInfo struct {
	// 消息
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// 消息大小
	Length int32 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	// 消息计数
	Cnt int32 `protobuf:"varint,3,opt,name=cnt,proto3" json:"cnt,omitempty"`
	// 其他信息
	Other string `protobuf:"bytes,4,opt,name=other,proto3" json:"other,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto1.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptorMessage, []int{0} }

func (m *UserInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserInfo) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *UserInfo) GetCnt() int32 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

func (m *UserInfo) GetOther() string {
	if m != nil {
		return m.Other
	}
	return ""
}

func init() {
	proto1.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto1.RegisterEnum("proto.FOO", FOO_name, FOO_value)
}

func init() { proto1.RegisterFile("message.proto", fileDescriptorMessage) }

var fileDescriptorMessage = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x29, 0x5c,
	0x1c, 0xa1, 0xc5, 0xa9, 0x45, 0x9e, 0x79, 0x69, 0xf9, 0x42, 0x12, 0x5c, 0xec, 0x50, 0x35, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x18, 0x17, 0x5b, 0x4e, 0x6a, 0x5e, 0x7a,
	0x49, 0x86, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x94, 0x27, 0x24, 0xc0, 0xc5, 0x9c, 0x9c,
	0x57, 0x22, 0xc1, 0x0c, 0x16, 0x04, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xf3, 0x4b, 0x32, 0x52, 0x8b,
	0x24, 0x58, 0xc0, 0x26, 0x40, 0x38, 0x5a, 0x3c, 0x5c, 0xcc, 0x6e, 0xfe, 0xfe, 0x42, 0xac, 0x5c,
	0x8c, 0x11, 0x02, 0x0c, 0x49, 0x6c, 0x60, 0xab, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x69,
	0x9b, 0x88, 0x07, 0x92, 0x00, 0x00, 0x00,
}
